baseURL = 'https://daviddawson.me/'
languageCode = 'en-us'
title = 'David Dawson'
theme = 'blog-theme'

[params]
  description = 'Personal blog about software development, distributed systems, and technology philosophy'
  author = 'David Dawson'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 3

[taxonomies]
  category = 'categories'
  tag = 'tags'

[permalinks]
  posts = '/:year/:month/:slug/'