name = "decap-oauth"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[env.production]
vars = { ALLOWED_DOMAINS = "daviddawson.me,daviddawson.pages.dev" }

[[env.production.secrets]]
name = "GITHUB_CLIENT_ID"

[[env.production.secrets]]
name = "GITHUB_CLIENT_SECRET"